#! /bin/bash

BIN="$(dirname $(realpath $0))/bin"

BASH_RC="$HOME/.bashrc"
ZSH_RC="$HOME/.zshrc"
FISH_CONFIG="$HOME/.config/fish/fish.config"

NEW_PATH="$BIN:$PATH"

if [ ! grep -q "$BIN" "$BASH_RC" ]; then
    echo "export PATH=$NEWPATH" >> $BASH_RC
fi

if [[ -f "$ZSH_RC" && ! grep -q "$BIN" "$ZSH_RC"]]; then
    echo "export PATH=$NEWPATH" >> $ZSH_RC
fi

if [[ -f "$FISH_CONFIG" && ! grep -q "$BIN" "$FISH_CONFIG" ]]; then
    echo "fish_add_path $BIN" >> $FISH_CONFIG
fi

chmod +x $BIN/playbgm